include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    avoid_print: ignore
    deprecated_member_use: ignore
    unnecessary_null_comparison: ignore
    unused_element: ignore
    unused_field: ignore
    unused_local_variable: ignore
