name: Ombro_Plus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1
  firebase_core:
  firebase_auth: ^6.0.2
  cloud_firestore:
  intl: any
  cupertino_icons: ^1.0.0
  image_picker: ^1.0.7
  url_launcher: ^6.3.2
  fl_chart: ^1.1.0
  dropdown_button2: ^2.3.9
  flutter_multi_formatter: ^2.13.10
  mask_text_input_formatter: ^2.9.0
  flutter_native_splash: ^2.4.6
  flutter_icons_null_safety: ^1.1.0 
  flutter_launcher_icons: ^0.14.4
  flutter_image_compress: ^2.4.0
  qr_flutter: ^4.1.0
  font_awesome_flutter: ^10.10.0
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  names_launcher: ^0.0.2

flutter:
  uses-material-design: true

  assets:
  - 'assets/images/logo-app.png'
  - 'assets/images/logo-app-imagem.png'
  - 'assets/images/exercicio.jpg'
  - 'assets/images/shoulder.png'

names_launcher:
  name: "Ombro Plus"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-app-imagem.png"

flutter_native_splash:
  color: "#0E382C"
  image: 'assets/images/logo-app-imagem.png'
  android: true
  ios: true
